# Identificador único del proyecto en SonarCloud
sonar.projectKey=osleivac_AUY1102-Pipeline
sonar.organization=oscar
sonar.host.url=https://sonarcloud.io/

# Especifica el lenguaje principal
sonar.language=js

# Define la carpeta donde están los archivos fuente
sonar.sources=src

# Excluye carpetas y archivos innecesarios
sonar.exclusions=**/node_modules/**,**/*.test.js,**/test/**,**/.git/**,**/.github/**

# Si tienes cobertura de pruebas, descomenta esta línea
# sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Opcional: si usas TypeScript, descomenta esta línea
# sonar.typescript.tsconfigPath=tsconfig.json