sonar.projectKey=osleivac_AUY1102-Pipeline
sonar.organization=oscar

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js,**/test/**,**/.git/**,**/.github/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
