sonar.projectKey=osleivac_AUY1102-Pipeline
sonar.organization=oleivac

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js,**/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
